/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * firstSetup.java
 *
 * Created on Aug 17, 2011, 3:24:30 PM
 */

package jdata;

/**
 *
 * @author oozzal
 */
public class firstSetup extends javax.swing.JFrame {

    private static String message = null;
    private static databaseObject dbObj = null;
    /** Creates new form firstSetup */
    public firstSetup() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstSetupInfo = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        rootPassPasswordField = new javax.swing.JPasswordField();
        setupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jData->firstSetup");
        setBounds(new java.awt.Rectangle(280, 250, 0, 0));
        setResizable(false);

        firstSetupInfo.setText("Enter MySQL root password for the first setup:");

        messageLabel.setForeground(java.awt.Color.red);
        messageLabel.setText("Nothing Entered");

        rootPassPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootPassPasswordFieldActionPerformed(evt);
            }
        });

        setupButton.setText("Setup");
        setupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Make sure that the MySQL service is sarted.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstSetupInfo)
                        .addComponent(messageLabel)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(rootPassPasswordField)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(setupButton)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstSetupInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rootPassPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setupButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rootPassPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootPassPasswordFieldActionPerformed
        // TODO add your handling code here:
        setup(rootPassPasswordField.getText());
    }//GEN-LAST:event_rootPassPasswordFieldActionPerformed

    private void setupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupButtonActionPerformed
        // TODO add your handling code here:
        setup(rootPassPasswordField.getText());
    }//GEN-LAST:event_setupButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstSetup().setVisible(true);
            }
        });
    }

    public void setup(String pass) {
        dbObj = new databaseObject("root", pass);
        dbObj.host = "jdbc:mysql://localhost/";
        if(!dbObj.loadDriver()) {
            System.out.println("Could not load driver");
        }
        if(!dbObj.getConnection()) {  //wrong root password
            message = "Wrong root password!";
            messageLabel.setText(message);
            rootPassPasswordField.setText("");
        } else { //now setup
            dbObj.query = "CREATE DATABASE IF NOT EXISTS " + dbObj.appName;
            dbObj.execute_update();
            dbObj.query = "GRANT ALL PRIVILEGES ON " + dbObj.appName + ".* TO '" + dbObj.appName + "_user'@'localhost' IDENTIFIED BY '" + dbObj.appName + "_pass'";
            dbObj.execute_update();
            dbObj.query = "CREATE TABLE IF NOT EXISTS " + dbObj.appName + ".users(username VARCHAR(50) NOT NULL UNIQUE KEY, password VARCHAR(50) NOT NULL)";
            dbObj.execute_update();
            if(dbObj.createUser()){
                dbObj.showDialog("root user created!");
            } else {
                dbObj.showDialog("error in root user creation");
            }
            dispose();
            new start().setVisible(true);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstSetupInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JPasswordField rootPassPasswordField;
    private javax.swing.JButton setupButton;
    // End of variables declaration//GEN-END:variables

}
