/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * manageUsers.java
 *
 * Created on Aug 18, 2011, 7:17:23 PM
 */

package jdata;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Uzzal Devkota
 */
public class manageUsers extends javax.swing.JFrame {

    public static databaseObject dbObj = null;
    /** Creates new form manageUsers */
    public manageUsers(databaseObject dbObject) {
        dbObj = dbObject;
        initComponents();
    }
    public manageUsers() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersListModel = new javax.swing.DefaultListModel();
        usersList = new javax.swing.JList(usersListModel);
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        filesListModel = new javax.swing.DefaultListModel();
        filesList = new javax.swing.JList(filesListModel);
        deleteButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("jData->manageUsers");
        setBounds(new java.awt.Rectangle(280, 250, 0, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        userLabel.setText("Username:");

        usersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(usersList);

        jLabel1.setText("Total files:");

        filesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        filesList.setEnabled(false);
        jScrollPane2.setViewportView(filesList);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        closeButton.setText("CLose");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fillLists();
    }//GEN-LAST:event_formWindowOpened

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteUser();
        fillLists();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageUsers().setVisible(true);
            }
        });
    }

    private void fillLists() {
        dbObj = new databaseObject();
        dbObj.query = "SELECT * FROM users";
        usersListModel.clear();
        filesListModel.clear();
        try {
            dbObj.ps = dbObj.con.prepareStatement(dbObj.query);
            dbObj.rs = dbObj.ps.executeQuery();
            while(dbObj.rs.next()) {//till the next element in the table is found
                usersListModel.addElement(dbObj.rs.getString("username"));
                String query = "SELECT COUNT(*) from " + dbObj.rs.getString("username") + "_files";
                PreparedStatement ps = dbObj.con.prepareStatement(query);
                ResultSet rs = ps.executeQuery();
                while(rs.next()) {//till the next element in the table is found
                    filesListModel.addElement(rs.getInt("COUNT(*)"));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void deleteUser() {
        if(!usersList.isSelectionEmpty()){
            String user = usersList.getSelectedValue().toString();
            if(!user.equals("root")){
                dbObj.query = "DELETE FROM users WHERE username='" + user + "'";
                dbObj.execute_update();
                dbObj.query = "DROP TABLE "+ user +"_files";
                dbObj.execute_update();
                dbObj.showDialog("User " + user + " deleted!");
            } else {
                dbObj.showDialog("Cannot delete root!");
            }
        } else {
            dbObj.showDialog("Please select a user to delete.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JList filesList;
    private javax.swing.DefaultListModel filesListModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel userLabel;
    private javax.swing.JList usersList;
    private javax.swing.DefaultListModel usersListModel;
    // End of variables declaration//GEN-END:variables

}
